param(
    [string]$MediaDir = "C:\mvp\media",
    [string]$MpvPath = "C:\mvp\mpv.exe",
    [int]$ImageDuration = 10
)

$Playlist = Join-Path $MediaDir "playlist.m3u"
$MpvArgs = "--fs --loop-playlist=inf --image-display-duration=$ImageDuration --no-osd-bar --really-quiet"

function Build-Playlist {
    $files = Get-ChildItem $MediaDir -File |
        Where-Object { $_.Extension -match 'mp4|avi|mkv|mov|jpg|jpeg|png' } |
        Sort-Object Name

    $list = @("#EXTM3U")
    foreach ($f in $files) {
        $list += $f.FullName
    }

    $list | Set-Content -Encoding UTF8 $Playlist
}

function Restart-Mpv {
    Get-Process mpv -ErrorAction SilentlyContinue | Stop-Process -Force
    Start-Process $MpvPath -ArgumentList "`"$Playlist`" $MpvArgs"
}

# ---- hide window ----
Add-Type @"
using System;
using System.Runtime.InteropServices;
public class Win32 {
    [DllImport("kernel32.dll")]
    public static extern IntPtr GetConsoleWindow();
    [DllImport("user32.dll")]
    public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
}
"@
[Win32]::ShowWindow([Win32]::GetConsoleWindow(), 0)

# ---- initial ----
Build-Playlist
Restart-Mpv

# ---- watcher ----
$fsw = New-Object System.IO.FileSystemWatcher $MediaDir
$fsw.IncludeSubdirectories = $false
$fsw.EnableRaisingEvents = $true

Register-ObjectEvent $fsw Created -Action { Build-Playlist; Restart-Mpv }
Register-ObjectEvent $fsw Deleted -Action { Build-Playlist; Restart-Mpv }
Register-ObjectEvent $fsw Renamed -Action { Build-Playlist; Restart-Mpv }

while ($true) { Start-Sleep 1 }
# SIG # Begin signature block
# MIIe0gYJKoZIhvcNAQcCoIIewzCCHr8CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU0DUpNghdoytJqZEzQgc+KYaF
# 9o2gghkWMIIGDjCCBPagAwIBAgITOQAAAFyYE8mVOeetMQABAAAAXDANBgkqhkiG
# 9w0BAQsFADBHMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxFjAUBgoJkiaJk/IsZAEZ
# FgZkaW94aWQxFjAUBgNVBAMTDWRpb3hpZC1EQzEtQ0EwHhcNMjUxMjEwMDc0NjQz
# WhcNMjYwNTAyMDMyMzAwWjBeMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxFjAUBgoJ
# kiaJk/IsZAEZFgZkaW94aWQxCzAJBgNVBAsTAml0MSAwHgYDVQQDDBfQktC+0LvQ
# vtCx0YPQtdCyINCb0LXQsjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
# AMUTNjilKrmT5wUC+N3DDFPbgX8/McUw05HWiQl607aGCsSXC83QWwwexysRZSJ0
# yxCRQzvbthyQTXDZpDEtA6D0Erlb8uZ21puu6MTFtYiVVN5+4liyUs/rl3ZCGXff
# Sl280zZZjJdB0yf7PYbFzIxEZ9VcXM25BjZ3HuAs8Kb88uYZdm7Bkc4Z+BqTFxlH
# pMvD1xZAid1vnMfjmiNETFcjd0tWeGWC6wCGftv77YQaKtWz69AtLTEh6uscM4y3
# 8Dddf5ifcCaNgkgZuz2tk3fIZkxv13oNhA060cSHrbpA3ruI337rmtTOPVn3P2He
# aXW8Tx+v14OnC7n020R2ScECAwEAAaOCAtowggLWMDoGCSsGAQQBgjcVBwQtMCsG
# IysGAQQBgjcVCILUgGz7/heE6YMi9PhJgsWbKyqH0/8I/9NMAgFoAgEDMBMGA1Ud
# JQQMMAoGCCsGAQUFBwMDMA4GA1UdDwEB/wQEAwIHgDAbBgkrBgEEAYI3FQoEDjAM
# MAoGCCsGAQUFBwMDMB0GA1UdDgQWBBR/cfWO4/E77CHtichNn25FYE2XsDAfBgNV
# HSMEGDAWgBSetaEC/dRf33iOFNlcIvdkpxtnNjCBywYDVR0fBIHDMIHAMIG9oIG6
# oIG3hoG0bGRhcDovLy9DTj1kaW94aWQtREMxLUNBKDEpLENOPWRjMSxDTj1DRFAs
# Q049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmln
# dXJhdGlvbixEQz1kaW94aWQsREM9bG9jYWw/Y2VydGlmaWNhdGVSZXZvY2F0aW9u
# TGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50MIHABggr
# BgEFBQcBAQSBszCBsDCBrQYIKwYBBQUHMAKGgaBsZGFwOi8vL0NOPWRpb3hpZC1E
# QzEtQ0EsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZp
# Y2VzLENOPUNvbmZpZ3VyYXRpb24sREM9ZGlveGlkLERDPWxvY2FsP2NBQ2VydGlm
# aWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MDMG
# A1UdEQQsMCqgKAYKKwYBBAGCNxQCA6AaDBh2b2xvYnVldi1sYUBkaW94aWQubG9j
# YWwwUAYJKwYBBAGCNxkCBEMwQaA/BgorBgEEAYI3GQIBoDEEL1MtMS01LTIxLTM5
# MjQ1NTM0MzMtMjI5ODI1MDc3OS0xODE2OTA1NjQ5LTEwOTc2MA0GCSqGSIb3DQEB
# CwUAA4IBAQAaeWY7jkmsFDcWjhJufM6Zdf1l0j004RXOGdOoL5P1/U20EM6XZ3fm
# L8sOQQca/6qCZ/3YrtQNnAOz/vuaKtuGOlzBgh4Vl687SNhPqVQUszImAuD9wRL5
# 047xfIAbzXZLHl3Pk3dJv913m5qRdMKZSmr17swJBIvvmd/UN2IAr/SiOALeUuwE
# cPyIt5Lx+uLydnff7MTq7ycs1KMpNNbXJsEg0LhoAaLhhLySY+NjIBlewOo+l40v
# VsFwxjgua0O9eSra7+gOimUy1NPkTR1ndF/KVcSEBOUL3zUPctM6BlfIFr7M0Sx1
# +QK/AcxoYG0AL4S5r8WNGPJ0Ikd9o0Q+MIIGFDCCA/ygAwIBAgIQeiOu2lNplg+R
# yD5c9MfjPzANBgkqhkiG9w0BAQwFADBXMQswCQYDVQQGEwJHQjEYMBYGA1UEChMP
# U2VjdGlnbyBMaW1pdGVkMS4wLAYDVQQDEyVTZWN0aWdvIFB1YmxpYyBUaW1lIFN0
# YW1waW5nIFJvb3QgUjQ2MB4XDTIxMDMyMjAwMDAwMFoXDTM2MDMyMTIzNTk1OVow
# VTELMAkGA1UEBhMCR0IxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDEsMCoGA1UE
# AxMjU2VjdGlnbyBQdWJsaWMgVGltZSBTdGFtcGluZyBDQSBSMzYwggGiMA0GCSqG
# SIb3DQEBAQUAA4IBjwAwggGKAoIBgQDNmNhDQatugivs9jN+JjTkiYzT7yISgFQ+
# 7yavjA6Bg+OiIjPm/N/t3nC7wYUrUlY3mFyI32t2o6Ft3EtxJXCc5MmZQZ8AxCbh
# 5c6WzeJDB9qkQVa46xiYEpc81KnBkAWgsaXnLURoYZzksHIzzCNxtIXnb9njZhol
# Gw9djnjkTdAA83abEOHQ4ujOGIaBhPXG2NdV8TNgFWZ9BojlAvflxNMCOwkCnzlH
# 4oCw5+4v1nssWeN1y4+RlaOywwRMUi54fr2vFsU5QPrgb6tSjvEUh1EC4M29YGy/
# SIYM8ZpHadmVjbi3Pl8hJiTWw9jiCKv31pcAaeijS9fc6R7DgyyLIGflmdQMwrNR
# xCulVq8ZpysiSYNi79tw5RHWZUEhnRfs/hsp/fwkXsynu1jcsUX+HuG8FLa2BNhe
# UPtOcgw+vHJcJ8HnJCrcUWhdFczf8O+pDiyGhVYX+bDDP3GhGS7TmKmGnbZ9N+Mp
# EhWmbiAVPbgkqykSkzyYVr15OApZYK8CAwEAAaOCAVwwggFYMB8GA1UdIwQYMBaA
# FPZ3at0//QET/xahbIICL9AKPRQlMB0GA1UdDgQWBBRfWO1MMXqiYUKNUoC6s2GX
# GaIymzAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADATBgNVHSUE
# DDAKBggrBgEFBQcDCDARBgNVHSAECjAIMAYGBFUdIAAwTAYDVR0fBEUwQzBBoD+g
# PYY7aHR0cDovL2NybC5zZWN0aWdvLmNvbS9TZWN0aWdvUHVibGljVGltZVN0YW1w
# aW5nUm9vdFI0Ni5jcmwwfAYIKwYBBQUHAQEEcDBuMEcGCCsGAQUFBzAChjtodHRw
# Oi8vY3J0LnNlY3RpZ28uY29tL1NlY3RpZ29QdWJsaWNUaW1lU3RhbXBpbmdSb290
# UjQ2LnA3YzAjBggrBgEFBQcwAYYXaHR0cDovL29jc3Auc2VjdGlnby5jb20wDQYJ
# KoZIhvcNAQEMBQADggIBABLXeyCtDjVYDJ6BHSVY/UwtZ3Svx2ImIfZVVGnGoUaG
# dltoX4hDskBMZx5NY5L6SCcwDMZhHOmbyMhyOVJDwm1yrKYqGDHWzpwVkFJ+996j
# KKAXyIIaUf5JVKjccev3w16mNIUlNTkpJEor7edVJZiRJVCAmWAaHcw9zP0hY3gj
# +fWp8MbOocI9Zn78xvm9XKGBp6rEs9sEiq/pwzvg2/KjXE2yWUQIkms6+yslCRqN
# XPjEnBnxuUB1fm6bPAV+Tsr/Qrd+mOCJemo06ldon4pJFbQd0TQVIMLv5koklInH
# vyaf6vATJP4DfPtKzSBPkKlOtyaFTAjD2Nu+di5hErEVVaMqSVbfPzd6kNXOhYm2
# 3EWm6N2s2ZHCHVhlUgHaC4ACMRCgXjYfQEDtYEK54dUwPJXV7icz0rgCzs9VI29D
# wsjVZFpO4ZIVR33LwXyPDbYFkLqYmgHjR3tKVkhh9qKV2WCmBuC27pIOx6TYvyqi
# YbntinmpOqh/QPAnhDgexKG9GX/n1PggkGi9HCapZp8fRwg8RftwS21Ln61euBG0
# yONM6noD2XQPrFwpm3GcuqJMf0o8LLrFkSLRQNwxPDDkWXhW+gZswbaiie5fd/W2
# ygcto78XCSPfFWveUOSZ5SqK95tBO8aTHmEa4lpJVD7HrTEn9jb1EGvxOb1cnn0C
# MIIGYjCCBMqgAwIBAgIRAKQpO24e3denNAiHrXpOtyQwDQYJKoZIhvcNAQEMBQAw
# VTELMAkGA1UEBhMCR0IxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDEsMCoGA1UE
# AxMjU2VjdGlnbyBQdWJsaWMgVGltZSBTdGFtcGluZyBDQSBSMzYwHhcNMjUwMzI3
# MDAwMDAwWhcNMzYwMzIxMjM1OTU5WjByMQswCQYDVQQGEwJHQjEXMBUGA1UECBMO
# V2VzdCBZb3Jrc2hpcmUxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDEwMC4GA1UE
# AxMnU2VjdGlnbyBQdWJsaWMgVGltZSBTdGFtcGluZyBTaWduZXIgUjM2MIICIjAN
# BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA04SV9G6kU3jyPRBLeBIHPNyUgVNn
# YayfsGOyYEXrn3+SkDYTLs1crcw/ol2swE1TzB2aR/5JIjKNf75QBha2Ddj+4NEP
# KDxHEd4dEn7RTWMcTIfm492TW22I8LfH+A7Ehz0/safc6BbsNBzjHTt7FngNfhfJ
# oYOrkugSaT8F0IzUh6VUwoHdYDpiln9dh0n0m545d5A5tJD92iFAIbKHQWGbCQNY
# plqpAFasHBn77OqW37P9BhOASdmjp3IijYiFdcA0WQIe60vzvrk0HG+iVcwVZjz+
# t5OcXGTcxqOAzk1frDNZ1aw8nFhGEvG0ktJQknnJZE3D40GofV7O8WzgaAnZmoUn
# 4PCpvH36vD4XaAF2CjiPsJWiY/j2xLsJuqx3JtuI4akH0MmGzlBUylhXvdNVXcjA
# uIEcEQKtOBR9lU4wXQpISrbOT8ux+96GzBq8TdbhoFcmYaOBZKlwPP7pOp5Mzx/U
# MhyBA93PQhiCdPfIVOCINsUY4U23p4KJ3F1HqP3H6Slw3lHACnLilGETXRg5X/Fp
# 8G8qlG5Y+M49ZEGUp2bneRLZoyHTyynHvFISpefhBCV0KdRZHPcuSL5OAGWnBjAl
# RtHvsMBrI3AAA0Tu1oGvPa/4yeeiAyu+9y3SLC98gDVbySnXnkujjhIh+oaatsk/
# oyf5R2vcxHahajMCAwEAAaOCAY4wggGKMB8GA1UdIwQYMBaAFF9Y7UwxeqJhQo1S
# gLqzYZcZojKbMB0GA1UdDgQWBBSIYYyhKjdkgShgoZsx0Iz9LALOTzAOBgNVHQ8B
# Af8EBAMCBsAwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDBK
# BgNVHSAEQzBBMDUGDCsGAQQBsjEBAgEDCDAlMCMGCCsGAQUFBwIBFhdodHRwczov
# L3NlY3RpZ28uY29tL0NQUzAIBgZngQwBBAIwSgYDVR0fBEMwQTA/oD2gO4Y5aHR0
# cDovL2NybC5zZWN0aWdvLmNvbS9TZWN0aWdvUHVibGljVGltZVN0YW1waW5nQ0FS
# MzYuY3JsMHoGCCsGAQUFBwEBBG4wbDBFBggrBgEFBQcwAoY5aHR0cDovL2NydC5z
# ZWN0aWdvLmNvbS9TZWN0aWdvUHVibGljVGltZVN0YW1waW5nQ0FSMzYuY3J0MCMG
# CCsGAQUFBzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNvbTANBgkqhkiG9w0BAQwF
# AAOCAYEAAoE+pIZyUSH5ZakuPVKK4eWbzEsTRJOEjbIu6r7vmzXXLpJx4FyGmcqn
# FZoa1dzx3JrUCrdG5b//LfAxOGy9Ph9JtrYChJaVHrusDh9NgYwiGDOhyyJ2zRy3
# +kdqhwtUlLCdNjFjakTSE+hkC9F5ty1uxOoQ2ZkfI5WM4WXA3ZHcNHB4V42zi7Jk
# 3ktEnkSdViVxM6rduXW0jmmiu71ZpBFZDh7Kdens+PQXPgMqvzodgQJEkxaION5X
# RCoBxAwWwiMm2thPDuZTzWp/gUFzi7izCmEt4pE3Kf0MOt3ccgwn4Kl2FIcQaV55
# nkjv1gODcHcD9+ZVjYZoyKTVWb4VqMQy/j8Q3aaYd/jOQ66Fhk3NWbg2tYl5jhQC
# uIsE55Vg4N0DUbEWvXJxtxQQaVR5xzhEI+BjJKzh3TQ026JxHhr2fuJ0mV68AluF
# r9qshgwS5SpN5FFtaSEnAwqZv3IS+mlG50rK7W3qXbWwi4hmpylUfygtYLEdLQuk
# NEX1jiOKMIIGgjCCBGqgAwIBAgIQNsKwvXwbOuejs902y8l1aDANBgkqhkiG9w0B
# AQwFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCk5ldyBKZXJzZXkxFDASBgNV
# BAcTC0plcnNleSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsx
# LjAsBgNVBAMTJVVTRVJUcnVzdCBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw
# HhcNMjEwMzIyMDAwMDAwWhcNMzgwMTE4MjM1OTU5WjBXMQswCQYDVQQGEwJHQjEY
# MBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMS4wLAYDVQQDEyVTZWN0aWdvIFB1Ymxp
# YyBUaW1lIFN0YW1waW5nIFJvb3QgUjQ2MIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
# MIICCgKCAgEAiJ3YuUVnnR3d6LkmgZpUVMB8SQWbzFoVD9mUEES0QUCBdxSZqdTk
# dizICFNeINCSJS+lV1ipnW5ihkQyC0cRLWXUJzodqpnMRs46npiJPHrfLBOifjfh
# pdXJ2aHHsPHggGsCi7uE0awqKggE/LkYw3sqaBia67h/3awoqNvGqiFRJ+OTWYmU
# CO2GAXsePHi+/JUNAax3kpqstbl3vcTdOGhtKShvZIvjwulRH87rbukNyHGWX5tN
# K/WABKf+Gnoi4cmisS7oSimgHUI0Wn/4elNd40BFdSZ1EwpuddZ+Wr7+Dfo0lcHf
# lm/FDDrOJ3rWqauUP8hsokDoI7D/yUVI9DAE/WK3Jl3C4LKwIpn1mNzMyptRwsXK
# rop06m7NUNHdlTDEMovXAIDGAvYynPt5lutv8lZeI5w3MOlCybAZDpK3Dy1MKo+6
# aEtE9vtiTMzz/o2dYfdP0KWZwZIXbYsTIlg1YIetCpi5s14qiXOpRsKqFKqav9R1
# R5vj3NgevsAsvxsAnI8Oa5s2oy25qhsoBIGo/zi6GpxFj+mOdh35Xn91y72J4RGO
# JEoqzEIbW3q0b2iPuWLA911cRxgY5SJYubvjay3nSMbBPPFsyl6mY4/WYucmyS9l
# o3l7jk27MAe145GWxK4O3m3gEFEIkv7kRmefDR7Oe2T1HxAnICQvr9sCAwEAAaOC
# ARYwggESMB8GA1UdIwQYMBaAFFN5v1qqK0rPVIDh2JvAnfKyA2bLMB0GA1UdDgQW
# BBT2d2rdP/0BE/8WoWyCAi/QCj0UJTAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/
# BAUwAwEB/zATBgNVHSUEDDAKBggrBgEFBQcDCDARBgNVHSAECjAIMAYGBFUdIAAw
# UAYDVR0fBEkwRzBFoEOgQYY/aHR0cDovL2NybC51c2VydHJ1c3QuY29tL1VTRVJU
# cnVzdFJTQUNlcnRpZmljYXRpb25BdXRob3JpdHkuY3JsMDUGCCsGAQUFBwEBBCkw
# JzAlBggrBgEFBQcwAYYZaHR0cDovL29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG
# 9w0BAQwFAAOCAgEADr5lQe1oRLjlocXUEYfktzsljOt+2sgXke3Y8UPEooU5y39r
# AARaAdAxUeiX1ktLJ3+lgxtoLQhn5cFb3GF2SSZRX8ptQ6IvuD3wz/LNHKpQ5nX8
# hjsDLRhsyeIiJsms9yAWnvdYOdEMq1W61KE9JlBkB20XBee6JaXx4UBErc+YuoSb
# 1SxVf7nkNtUjPfcxuFtrQdRMRi/fInV/AobE8Gw/8yBMQKKaHt5eia8ybT8Y/Ffa
# 6HAJyz9gvEOcF1VWXG8OMeM7Vy7Bs6mSIkYeYtddU1ux1dQLbEGur18ut97wgGwD
# iGinCwKPyFO7ApcmVJOtlw9FVJxw/mL1TbyBns4zOgkaXFnnfzg4qbSvnrwyj1Ni
# urMp4pmAWjR+Pb/SIduPnmFzbSN/G8reZCL4fvGlvPFk4Uab/JVCSmj59+/mB2Gn
# 6G/UYOy8k60mKcmaAZsEVkhOFuoj4we8CYyaR9vd9PGZKSinaZIkvVjbH/3nlLb0
# a7SBIkiRzfPfS9T+JesylbHa1LtRV9U/7m0q7Ma2CQ/t392ioOssXW7oKLdOmMBl
# 14suVFBmbzrt5V5cQPnwtd3UOTpS9oCG+ZZheiIvPgkDmA8FzPsnfXW5qHELB43E
# T7HHFHeRPRYrMBKjkb8/IN7Po0d0hQoF4TeMM+zYAJzoKQnVKOLg8pZVPT8xggUm
# MIIFIgIBATBeMEcxFTATBgoJkiaJk/IsZAEZFgVsb2NhbDEWMBQGCgmSJomT8ixk
# ARkWBmRpb3hpZDEWMBQGA1UEAxMNZGlveGlkLURDMS1DQQITOQAAAFyYE8mVOeet
# MQABAAAAXDAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZ
# BgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYB
# BAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUVaBADiE45x6/l5Xp7J8f3kZB/ggwDQYJ
# KoZIhvcNAQEBBQAEggEAXXnynNiKUQ/BH3UFDDNx7cTykXBvvbv9gwrPcTKxuNAe
# UqX71kDpS4aOwGqTIQRi/3+h9bde0FvbJzBYtRJtp4q5cfdcsa+4nVWylvnR1Zoo
# 44kh+xppIPRol9yrkziwUXiVWdCRhRBvvYB1UPKF+UQXlEC1hXAs9g2iy/YJoqo7
# Jr5XFAi8z5WSQToxBz955+gk/ZIXnLw2dfalFYAiMBWk+ZajiNEIxNUJpGsjRUYV
# AyaDrRO/DnfElWlkL7BEXbXhLKnhw0ApM2+Kwai9NZY8VMUehX8RY3SDG6S32A/+
# pQcsfTMUBmAcb3CX0U8EvdIY/BjYr2XTHQEvr9IKP6GCAyMwggMfBgkqhkiG9w0B
# CQYxggMQMIIDDAIBATBqMFUxCzAJBgNVBAYTAkdCMRgwFgYDVQQKEw9TZWN0aWdv
# IExpbWl0ZWQxLDAqBgNVBAMTI1NlY3RpZ28gUHVibGljIFRpbWUgU3RhbXBpbmcg
# Q0EgUjM2AhEApCk7bh7d16c0CIetek63JDANBglghkgBZQMEAgIFAKB5MBgGCSqG
# SIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTI2MDEyMzA3NTgz
# MFowPwYJKoZIhvcNAQkEMTIEMDxeRXURwSej+0TOzKl60qv90RyE2CQ5WGMcX7i8
# VfhQXw6yhhiz1vK2XplM+DbH4DANBgkqhkiG9w0BAQEFAASCAgDBbE6kDtwqzWNl
# cokj+9y6Ex1PkcPLZrQKJ/qDJUKBGfknt19n0iPAVpbw0i8NRE25XO6dTvgnsZVg
# QkLdrlrQeXZDo3X5iEINklYhuA6nH5BehgOqAw8AyvbNB49vUaHBj4kDNn248gyV
# tcaEKYvNH3UAvKnOudviOKx6IameqyCT4x+v52XoqSiKBaeZxK9jG9U2vnNGPUkX
# TDSkr85s04UjmpzRnzFL2y1JwJbRAu5dhxOTzbVSqjnC8G7rMN7Xzs6EgxDG9SVc
# OBJVFxTW7C8ET8zavHe4vFrtAbNWAQTAZavvPsLT+vPwTMnJsXtJZ+vYQE1b2k82
# lOANFubqrnGV0SDmqlcyAh1YVThuDFRAw/OxSY3ZFM/dxIwEe9fUIwhG60WwCVTv
# 9M18DP/whYFkJXxE3pPGanDI24cxtnDd7+jJA9zC+c5Y5P9U5y42se4ELlxPiYR6
# NoMlgbr7+gPMMiiLRK2L4aadn3Sn9LotK1nkH4KXNyy1uTt6If3rYpJyrj9jbrFM
# Voa7ASfih9VFUpMiGjJgOSpqtx8wHBXkDz3GV9OT7ueOsX3k5PjY1CKNHoBmGMRk
# azZ+AtWCewfMIpso6Te4vocjGamIB4i2flt5+cr9LIH+jL8njDGNte5Iv0z82/yB
# EH0IT9TDa7TfiDju+3xfKXwm2VBnlQ==
# SIG # End signature block
